services:
  - type: background-worker
    name: telegram-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: your_bot_token_here
      - key: SUPABASE_URL
        value: your_supabase_url_here
      - key: SUPABASE_KEY
        value: your_supabase_key_here
